# Generated by Django 4.1 on 2022-10-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="upload/images")),
                ("name", models.CharField(max_length=50)),
                ("price", models.IntegerField(default=0)),
                ("original_price", models.IntegerField(default=0)),
            ],
        ),
    ]
