# Generated by Django 4.1 on 2022-10-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Features",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("big_image", models.ImageField(upload_to="upload/images")),
                ("first_image", models.ImageField(upload_to="upload/images")),
                ("second_image", models.ImageField(upload_to="upload/images")),
                ("third_image", models.ImageField(upload_to="upload/images")),
                ("forth_image", models.ImageField(upload_to="upload/images")),
                ("name", models.CharField(max_length=50)),
                ("desc", models.TextField()),
                ("price", models.IntegerField(default=0)),
                ("original_price", models.IntegerField(default=0)),
            ],
        ),
    ]
